CREATE TABLE FAGGRUPPE
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    navn VARCHAR(100)
);

CREATE TABLE ANSATT
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    fornavn      VARCHAR(100),
    faggruppe_id INTEGER FOREIGN KEY REFERENCES FAGGRUPPE (id)
);

INSERT INTO FAGGRUPPE (navn)
VALUES ('Java & JVM');
INSERT INTO FAGGRUPPE (navn)
VALUES ('APIer');


INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Sindre', 1);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Even', 1);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('John', 1);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Martine', 1);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Nicklas', 1);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Ole', 1);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Tia', 1);


INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Sigurd', 2);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Alexandra', 2);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Christian', 2);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Emil', 2);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Knut', 2);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Rune', 2);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Simen', 2);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Thomas', 2);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Thorstein', 2);
INSERT INTO ANSATT (fornavn, faggruppe_id)
VALUES ('Øystein', 2);
